title: Emojis for grown-ups
description: A proposal for 31 new emojis that go beyond the hugs and kisses of the standard emoji set.
baseurl: "/emoji"
url: ""
markdown: kramdown
exclude:
  - build/
  - emoji/
  - emojis.json
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - LICENSE-GRAPHICS
  - Makefile
  - NOTICE
  - README.md
  - package-lock.json
  - package.json
  - Pipfile
  - Pipfile.lock
  - png/
  - setup.cfg
  - twemoji-color-font/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

fontname: Emoji
fontname_try: EmojiTry
