title: Emojis for grown-ups
description: A proposal for 31 new emojis that go beyond the hugs and kisses of the standard emoji set.
baseurl: "/emoji"
url: ""
markdown: kramdown
exclude:
  - emoji.csv
  - emoji.py
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - LICENSE-GRAPHICS
  - Makefile
  - NOTICE
  - README.md
  - package-lock.json
  - package.json
  - png/
  - twemoji-color-font/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

fontname: Emoji
